#!/usr/bin/env zsh
# go up X directories or 1
upx() {
    local TEMPSTRING="cd "
    if [ -n "${1}" ] && [ "${1}" = "${1%%[!0-9]*}" ]; then
        for ((i = 0; i < $1; i++))
	do
	    cd ..
	    TEMPSTRING=$TEMPSTRING"../"
	done
    else
        cd ..
	TEMPSTRING=$TEMPSTRING".."
    fi
    if (( $# == 2 )); then
	cd "$2"
    	TEMPSTRING=$TEMPSTRING"$2"
    fi
    echo "$TEMPSTRING"
}
